AllCops:
 Exclude:
   - '**/Rakefile'
   - 'vendor/**/*'
   - 'spec/fixtures/**/*'
   - 'spec/*_helper.rb'
   - 'tmp/**/*'
   - 'bin/**/*'
   - 'db/**/*'
   - 'config/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
 Max: 105